//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOS.LearningStyle.FinalYear.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseGrade
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> Credits { get; set; }
        public string UserId { get; set; }
    }
}
